export const easyWords = [
    "ACATAR","ACELERA","ALERTA","ALTOS","AMIGOS","ANULAR","APROVA","ATIVOS","BAIXOS","BANCO",
    "BEIJO","BRANCO","BRINCA","BRINCO","CAIXAS","CANTAR","CEGO","CHUVA","CIDADE","COBRA",
    "COLHER","COMIDA","COMPRAR","CONTA","CORRER","CRESCA","CURIOSO","CURTIR","DESEJO","DIZER",
    "DIZIMAR","DOENTE","DORMIR","ENTRAR","ESCOLA","ESPADA","ESPERA","EXEMPLO","FALAR","FALHA",
    "FAVOR","FELIZ","FESTAS","FOGO","GANHA","GARFO","GERAL","GRADE","GRANDE","HANGAR","HORA",
    "HONRA","HORTA","HUMANO","JANELA","JANTAR","JEITO","JOGOS","JUNTOS","LARGO","LEVE","LICOR",
    "LOCUTOR","LOUCO","LUZES","MELHOR","MENTIR","MOEDA","MUDAR","NADAR","NUVEM","OBRAS",
    "OFERTA","OLHAR","PAGAR","PASSA","PENSAR","PERDA","PESCA","PIADA","PODER","PRATA","QUEIMA",
    "QUANDO","REDE","ROUPAS","SALTO","SEDOSO","SORTE","TARDE","TROUXE","URGIR","URNA","USAR",
    "VENDA","VIDA","VIVER","VOLTA","ZEBRA","ZERO"
]

export const midWords = [
    "AEROPORTO","ACADEMIA","ACOLHEDOR","ANALISAR","ANATOMIA","APROVEITAR","ASSUSTADOR",
    "AUTOESTIMA","BENEVOLENTE","BICICLETA","BRILHANTE","BRINCADEIRA","CONVENCER","CLARAMENTE",
    "COMPLEMENTO","CRESCIMENTO","CURIOSIDADE","DESENVOLVER","DESPERTAR","DETERMINAR",
    "DOMINANTE","EFICIENTE","ELETRIZAR","ENCANTAR","ENTENDIMENTO","ESCANDALOSO","EXPERIENTE",
    "EXPERIMENTAR","FASCINANTE","FLORESTA","FRATERNIDADE","FORTALEZA","GARANTIA","GELADEIRA",
    "GENEROSIDADE","GLAMOUROSO","HABILIDOSO","HONESTIDADE","HORIZONTE","HOSPITAL","IMPORTANTE",
    "IMIGRANTE","INFLUENTE","INSISTIR","INSPIRADOR","INTELIGENTE","INTERESSANTE","IMPRESSIONAR",
    "JABUTICABA","JORNALISTA","JUSTIFICAR","JUVENTUDE","LEALDADE","LEGITIMAR","LIBERDADE",
    "LINGUAGEM","LUMINOSO","MAGNITUDE","MARAVILHOSO","METAMORFOSE","MELHORAR","MILAGROSO",
    "NARRADOR","NASCIMENTO","NOVEMBRO","NUTRIENTE","OBSERVAR","OPORTUNO","ORGANIZAR","OTIMISTA",
    "PREOCUPADO","PROCRASTINAR","PROCURAR","PROGRESSO","PROPRIEDADE","QUADRILHA","QUARENTENA",
    "QUESTIONAR","REALIZAR","RECONHECER","RELEVANTE","RESTAURANTE","SABEDORIA","SALVADOR",
    "SIMPLIFICAR","SINTONIA","SUBMETER","TELEFONE","TRADICIONAL","TRANQUILIZAR","TURBINADO",
    "ULTRAPASSAR","ULTRAVIOLETA","UNIFORTE","UNIVERSO","URBANIDADE","VALORIZAR","VANTAJOSO",
    "VITALIDADE","VIVIFICAR"
]

export const hardWords = [
    "ADMINISTRATIVO","AMBIENTALISTA","ANTICONSTITUCIONAL","ANTIMILITARISTA","ARTIFICIALMENTE",
    "AUTODIDATISMO","BIODIVERSIDADE","BIOELETRICIDADE","BIOLOGICAMENTE","CATASTROFISTAS",
    "CERTIFICADORES","COLECIONADORA","COLONIZADORES","COMPLEMENTARES","COMPREENDIDOS",
    "CONSEQUENCIAL","CONTEXTUALIZAR","CONTROVERSIAS","COOPERATIVISMO","CORRESPONDENTE",
    "CRIMINALIDADES","CRONOMETRISTA","DECIDIDAMENTE","DEMOCRATIZADO","DESENVOLVIMENTO",
    "DESTRUTURADAS","DIVERSIFICADOS","ELETRIFICADOR","EMPREENDEDORES","ENGENHEIRISMOS",
    "ESTABILIZADAS","ESTATISTICISTA","EVOLUCIONISMO","EXEMPLIFICADO","EXPERIMENTADOS",
    "EXTERIORIZADOS","EXTRACONSTITUCIONAL","FUNDAMENTANDO","GENERALIZADOS","HABILITACIONES",
    "HARMONIZADORES","HOSPITALIDADE","HUMANITARISMO","IDEALIZADORES","IDENTIFICADORES",
    "IMORTALIZADAS","IMPARCIALIDADE","IMPRESSIONANTE","IMPRESSIONISMOS","INCONSTITUCIONAL",
    "INSTITUCIONAIS","INTELIGIBILIDADE","INTERCONECTADOS","INTERDEPENDENTE","LEGITIMIDADES",
    "MAGNIFICAMENTE","MAJESTOSIDADE","MECANICAMENTE","METICULOSIDADE","METODOLOGICAMENTE",
    "MODERNIZADORAS","MONITORAMENTOS","MONOTONICIDADE","NACIONALIDADE","NATURALIDADES",
    "NECESSITAREMOS","NECESSITASSEM","NEOCONSERVADORES","OBJETIVIDADES","PECULIARIDADES",
    "PERFECCIONISMO","PERSEVERANTES","POSITIVAMENTE","PREDOMINANTEMENTE","PRESENTEAMENTE",
    "PROFISSIONALISMO","PROGRESSIVAMENTE","PROPAGANDISTA","PROTAGONISMOS","PROVAVELMENTE",
    "QUALIFICATIVO","RECONHECIMENTO","RECUPERADORAS","REDUZIDAMENTE","REESTRUTURADOS",
    "REFLEXIVAMENTE","REGIONALISMOS","RESPONSABILIDADE","SATISFAZEDORAS","SISTEMATICAMENTE",
    "SOLIDARIEDADE","SUSTENTABILIDADE","TENDENCIOSAMENTE","TRANSPARENTEMENTE","TRASCENDENTES",
    "TRANSPORTADOR","UNIVERSALIDADES","UTILIZABILIDADE","VANTAJOSAMENTE","VULNERABILIDADE"
]

// Esta função irá misturar as letras do alfabeto e retornar um array delas
export function LetterMixer(){
    let letters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
    const mixedLetters = []
  
    for (let i = 0; i < 200; i++) {
        let randomString = ''

        for (let j = 0; j < 8; j++) {
            let randomIndex = Math.floor(Math.random() * letters.length)
            let randomLetter = letters.charAt(randomIndex)
            randomString += randomLetter
        }

        mixedLetters.push(randomString)
    }

    return mixedLetters
}